const data = ["Clean your hands often","Cough or sneeze in your bent elbow - not your hands!","Avoid touching your eyes, nose and mouth",
"Limit social gatherings and time spent in crowded places",
"Avoid close contact with someone who is sick",
"Clean and disinfect frequently touched objects and surfaces","Use an alcohol-based hand sanitizer that contains at least 60% alcohol if soap and water are not available.",
"If you have a fever, cough and difficulty breathing, seek medical attention immediately.",
"Keep in mind the travel advisory set out by the Ministry of Health and Welfare.",
"We won’t have a society if we destroy the environment.","Unplug chargers, turn off lights and appliances not in use like computers, laptops, and phones when you leave for the day.",
"Replace regular light bulbs in your home with compact fluorescent bulbs",
"Join the carpool or public transportation to save fuel and its cost.",
"Avoid using disposable cup or coffee mug at work in order to save space in the landfill and energy. You can bring your own ceramic cup or coffee mug to work.",
"When you make purchases, try to opt for the brands that use recyclable packaging.","Bring your meal in a reusable container and don’t buy an additional plastic container for it. Don’t generate waste with a plastic fork and plastic takeout container. Use a reusable container if bringing in lunch from home.",
"Start a recycling program in your home, office or community.",
"Start paying your bills online and ask companies to stop paper bills from being sent to you. Print and copy on both sides of the paper. It helps to save paper and trees.",
"Use reusable grocery bags rather than plastic bags",
"Get your IT equipment like computers, laptop, printer, and phones recycled or decomposed in order to reduce related air pollution and water pollution. It can take a million years to decompose. Contact a company offers IT equipment recycling or disposal services in your area. ",
"Use a more eco-friendly disposable or cloth in place of nappy of the child as it adds million tons of waste in landfills each year.",
"Recycle newspaper, bows and gift bags by reusing them. You can also create something unique by using old newspaper, maps, and cloth.",
"Instead of purchasing a plastic water bottle, buy an appropriate reusable container. A plastic bottle takes thousands of years to decompose and because it’s not recycled or biodegradable.",
"Plant a tree to reduce air pollution as shady landscape enhances the value of your property and reduce the energy consumption","Put the cruise control button on your car to work as you can get better mileage. With increasing gasoline prices, this is a boon for your budget and the environment too.",
"You can save about 10% of your energy use by adjusting your thermostat 1% cooler in winter and 1% higher in summer.",
"Try to get your phone recycled as it introduces very harmful and toxic substances into the environment and go into landfills.",
"Maintain your vehicle by regularly checking the air filter and giving it a clean. This will help your car more efficiently. It’s also important to inflate your tyres to a specific pressure as it reduces tyre-wear and helps the fuel economy.",
"You can conserve energy in your home by Setting your freezer temperature 0-5 ",
"Buy wooden toys instead of throwaway plastic toys","Take the stairs instead of using lifts.",
"The less you print, the less paper is used. Trees are cut down for paper. Therefore, the less you print, the fewer trees are cut down. In the long run, this could really add up to a lot of saved trees.",
"If you need to print, then print on both sides of the page. This will cut down the paper consumption by half, which saves half the number of trees in a forest.",
"In the same way, printing less causes less of a demand for paper; getting your bills through e-mail instead of a printed copy in the mail will decrease the demand for paper.",
"The FSC (Forest Stewardship Council) monitors that these products were sourced in an environmentally responsible way; if a product is not FSC Certified, boycott it, as you will then be supporting unsustainable deforestation by buying and funding these products.",
"Bamboo is easily sustainable and grows to maturity within five years, a lot faster than trees. They have exactly the same functions as well. Try to use bamboo paper as much as possible to lower the demand for paper produced by trees.",
"Again, this creates less of a demand for paper. Digital books are also more convenient as you have an endless supply of books on a single device. You can also read from a digital device in the dark, unlike with a book printed on paper.",
"If you still prefer to read the real thing, borrow books from your local library. It’s cost-efficient and environmentally conscious. Books are what you can always borrow, share and donate.",
"Most magazines offer the exact same content online if you sign up for a subscription with them. You will also receive the content immediately after it is released instead of waiting.",
"This will let your friends know you care about them and also the environment.","If you think this is tacky, opt for a recyclable gift bag. Explorers even love playing with cardboard boxes, empty toilet paper and paper towel rolls, and also shoeboxes. Boxes can become palace, forts and superhero headquarters, toilet paper rolls turn into binoculars and bird feeders, and paper towel rolls become spotting scopes and periscopes.",
"Use containers that can be used again and again for your food, trinkets, and just anything.",
"While paper plates and cups are convenient, they are not an environmentally aware of choice.",
"Use the hand dryer in the bathroom instead of paper towels.",
"If you need paper towels, buy tree-free or recycled paper towels instead of paper towels made from tree pulp.",
"There are also other tree-free options available.",
"Paper diapers are a strain on the environment. Many communities have diaper service that will pick up dirty diapers and leave clean ones.",
"You’ll pay less for it and help prevent deforestation."
];