const data = [
    "Clean your hands often","Cough or sneeze in your bent elbow - not your hands!",
    "Avoid touching your eyes, nose and mouth",
"Limit social gatherings and time spent in crowded places",
"Avoid close contact with someone who is sick",
"Clean and disinfect frequently touched objects and surfaces",
"Use an alcohol-based hand sanitizer that contains at least 60% alcohol if soap and water are not available.",
"If you have a fever, cough and difficulty breathing, seek medical attention immediately.",
"Keep in mind the travel advisory set out by the Ministry of Health and Welfare.",
"We won’t have a society if we destroy the environment.","Unplug chargers, turn off lights and appliances not in use like computers, laptops, and phones when you leave for the day.",
"Replace regular light bulbs in your home with compact fluorescent bulbs",
"Join the carpool or public transportation to save fuel and its cost.",
"When you make purchases, try to opt for the brands that use recyclable packaging.",
"Start a recycling program in your home, office or community.",
"Use reusable grocery bags rather than plastic bags",
"Use a more eco-friendly disposable or cloth in place of nappy of the child as it adds million tons of waste in landfills each year.",
"Recycle newspaper, bows and gift bags by reusing them. You can also create something unique by using old newspaper, maps, and cloth.",
"Plant a tree to reduce air pollution as shady landscape enhances the value of your property and reduce the energy consumption",
"Put the cruise control button on your car to work as you can get better mileage. With increasing gasoline prices, this is a boon for your budget and the environment too.",
"You can save about 10% of your energy use by adjusting your thermostat 1% cooler in winter and 1% higher in summer.",
"Try to get your phone recycled as it introduces very harmful and toxic substances into the environment and go into landfills.",
"You can conserve energy in your home by Setting your freezer temperature 0-5 ",
"Buy wooden toys instead of throwaway plastic toys",
"Take the stairs instead of using lifts.",
"The less you print, the less paper is used. Trees are cut down for paper. Therefore, the less you print, the fewer trees are cut down. In the long run, this could really add up to a lot of saved trees.",
"If you need to print, then print on both sides of the page. This will cut down the paper consumption by half, which saves half the number of trees in a forest.",
"In the same way, printing less causes less of a demand for paper; getting your bills through e-mail instead of a printed copy in the mail will decrease the demand for paper.",
"If you still prefer to read the real thing, borrow books from your local library. It’s cost-efficient and environmentally conscious. Books are what you can always borrow, share and donate.",
"Most magazines offer the exact same content online if you sign up for a subscription with them. You will also receive the content immediately after it is released instead of waiting.",
"This will let your friends know you care about them and also the environment.",
"Use containers that can be used again and again for your food, trinkets, and just anything.",
"While paper plates and cups are convenient, they are not an environmentally aware of choice.",
"Use the hand dryer in the bathroom instead of paper towels.",
"If you need paper towels, buy tree-free or recycled paper towels instead of paper towels made from tree pulp.",
"There are also other tree-free options available.",
"Paper diapers are a strain on the environment. Many communities have diaper service that will pick up dirty diapers and leave clean ones.",
"You’ll pay less for it and help prevent deforestation."
];

exports.data = data